# docker-compose.yml  (replace your service section)
services:
  jekyll:
    build: .
    platform: linux/arm64/v8 # ← M-series Mac
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll # your site
      - vendor_bundle:/usr/local/bundle # ← persist the gems
    environment:
      - JEKYLL_ENV=development

volumes:
  vendor_bundle: # named volume lives outside containers
